Percentage Improvement in Eqpt Efficiency Standards above BAU[cement and other carbonates,electricity if] = 0.068
Percentage Improvement in Eqpt Efficiency Standards above BAU[natural gas and petroleum systems,electricity if] = 0.0605
Percentage Improvement in Eqpt Efficiency Standards above BAU[iron and steel,electricity if] = 0.07
Percentage Improvement in Eqpt Efficiency Standards above BAU[chemicals,electricity if] = 0.075
Percentage Improvement in Eqpt Efficiency Standards above BAU[coal mining,electricity if] = 0.064
Percentage Improvement in Eqpt Efficiency Standards above BAU[waste management,electricity if] = 0.064
Percentage Improvement in Eqpt Efficiency Standards above BAU[agriculture,electricity if] = 0.0665
Percentage Improvement in Eqpt Efficiency Standards above BAU[other industries,electricity if] = 0.0694
